/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smart_store2;
import java.awt.Window;
import javax.swing.Timer;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author MINEDUCYT
 */
public class login extends javax.swing.JFrame {

private int intentosRestantes = 3;
private Timer timerBloqueo;
private int segundosRestantes = 120;
private javax.swing.JLabel lblCronometro; // Para mostrar el conteo visualmente

    
    
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
       // private javax.swing.JLabel lblCronometro; // Etiqueta para mostrar el conteo
 // Crear etiqueta del cronómetro
    lblCronometro = new javax.swing.JLabel();
    lblCronometro.setText(""); // Inicia vacía
    lblCronometro.setForeground(java.awt.Color.RED); // Color rojo (opcional)

    // Agregar al panel visual
    jPanel1.add(lblCronometro);

    // Posicionarla (si usas layout absoluto o lo necesitas manual)
    lblCronometro.setBounds(150, 350, 200, 20); // x, y, ancho, alto (ajústalo según tu diseño)
    }

    
    private void bloquearLogin() {
    btn_inicio.setEnabled(false);
    segundosRestantes = 120; // 2 minutos
    lblCronometro.setText("Espera: 2:00 minutos");

    timerBloqueo = new Timer(1000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            segundosRestantes--;

            int minutos = segundosRestantes / 60;
            int segundos = segundosRestantes % 60;
            lblCronometro.setText(String.format("Espera: %d:%02d minutos", minutos, segundos));

            if (segundosRestantes <= 0) {
                timerBloqueo.stop();
                btn_inicio.setEnabled(true);
                intentosRestantes = 3;
                lblCronometro.setText("");
                javax.swing.JOptionPane.showMessageDialog(null, "Ya puedes volver a intentarlo.");
            }
        }
    });

    timerBloqueo.start();
}

    
    
    
    
    
   
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        psw_contraseña = new javax.swing.JPasswordField();
        btn_salir = new javax.swing.JButton();
        btn_inicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblconometro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoTienda.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(127, 6, 176, 163);
        jPanel1.add(txt_nombre);
        txt_nombre.setBounds(137, 204, 180, 24);
        jPanel1.add(psw_contraseña);
        psw_contraseña.setBounds(137, 278, 180, 22);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir);
        btn_salir.setBounds(360, 10, 46, 53);

        btn_inicio.setText("iniciar sesión");
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(btn_inicio);
        btn_inicio.setBounds(170, 320, 110, 24);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(57, 204, 45, 45);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contra.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(57, 255, 45, 45);

        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 180, 44, 16);

        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Contraseña");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 250, 65, 16);

        lblconometro.setBackground(new java.awt.Color(255, 255, 255));
        lblconometro.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblconometro);
        lblconometro.setBounds(30, 400, 160, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo01.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
    dispose(); // Cierra este JFrame
    
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
    
     if (timerBloqueo != null && timerBloqueo.isRunning()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debes esperar a que termine el conteo.");
        return;
    }

    String usuario = txt_nombre.getText().trim();
    String contraseña = new String(psw_contraseña.getPassword());

    if (usuario.equals("admin") && contraseña.equals("1234")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso");

        javax.swing.JFrame nuevaVentana = new javax.swing.JFrame("Bienvenido");
        nuevaVentana.setSize(400, 300);
        nuevaVentana.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        nuevaVentana.setLocationRelativeTo(null);
        nuevaVentana.setVisible(true);

        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    } else {
        intentosRestantes--;

        if (intentosRestantes > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos. Te quedan " + intentosRestantes + " intentos.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Demasiados intentos. Debes esperar 2 minutos.");
            bloquearLogin();
        }
    }
    }//GEN-LAST:event_btn_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblconometro;
    private javax.swing.JPasswordField psw_contraseña;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
